"""empty message

Revision ID: 0782fc8a2378
Revises: 674327c57938
Create Date: 2023-01-26 18:43:07.064986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0782fc8a2378'
down_revision = '674327c57938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('speed', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('capacity', sa.String(length=250), nullable=False))
        batch_op.drop_column('costinCredits')
        batch_op.drop_column('vehicleClass')
        batch_op.drop_column('cargoCapacity')
        batch_op.drop_column('maxAtmSpeed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maxAtmSpeed', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cargoCapacity', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vehicleClass', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('costinCredits', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('capacity')
        batch_op.drop_column('cost')
        batch_op.drop_column('speed')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
