"""empty message

Revision ID: 12291da93ec0
Revises: 0782fc8a2378
Create Date: 2023-01-26 19:34:24.611844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12291da93ec0'
down_revision = '0782fc8a2378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('is_active')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
