"""empty message

Revision ID: 674327c57938
Revises: 2af7b88a187c
Create Date: 2023-01-26 18:40:34.459306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674327c57938'
down_revision = '2af7b88a187c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
